// background.js — Test Action Recorder Service Worker
// Relays events from content scripts to the popup and persists state

const state = {
  recording: false,
  events: [],
};

// ─── Code Generator ───────────────────────────────────────────────────────

function eventToCode(event) {
  const sel = event.selector.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  switch (event.type) {
    case "click":
      return `await driver.findElement(By.css("${sel}")).click();`;

    case "input":
      const val = (event.value || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      return `await driver.findElement(By.css("${sel}")).sendKeys("${val}");`;

    case "select":
      const opt = (event.value || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      return (
        `{\n` +
        `  const el = await driver.findElement(By.css("${sel}"));\n` +
        `  await new Select(el).selectByValue("${opt}");\n` +
        `}`
      );

    default:
      return `// Unknown event: ${event.type}`;
  }
}

function buildCode(events) {
  if (events.length === 0) return "";

  const lines = [
    `// Generated by Test Action Recorder`,
    `// Selenium WebDriver — JavaScript (Node.js)`,
    ``,
    `const { Builder, By, Key } = require("selenium-webdriver");`,
    ``,
    `(async function run() {`,
    `  const driver = await new Builder().forBrowser("chrome").build();`,
    `  try {`,
    ...events.map((e) =>
      eventToCode(e)
        .split("\n")
        .map((l) => `    ${l}`)
        .join("\n")
    ),
    `  } finally {`,
    `    await driver.quit();`,
    `  }`,
    `})();`,
  ];

  return lines.join("\n");
}

// ─── Message Handling ─────────────────────────────────────────────────────

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  // Event from content script
  if (msg.action === "TAR_EVENT" && state.recording) {
    state.events.push(msg.event);
    const code = buildCode(state.events);
    chrome.storage.local.set({ tarEvents: state.events, tarCode: code });

    // Notify popup if open
    chrome.runtime.sendMessage({ action: "TAR_UPDATE", code, events: state.events }).catch(() => {});
    sendResponse({ ok: true });
    return true;
  }

  // Popup: get current state
  if (msg.action === "TAR_GET_STATE") {
    sendResponse({
      recording: state.recording,
      events: state.events,
      code: buildCode(state.events),
    });
    return true;
  }

  // Popup: start recording
  if (msg.action === "TAR_START_RECORDING") {
    state.recording = true;
    chrome.storage.local.set({ tarRecording: true });

    // Inject + activate content script in active tab
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      const tab = tabs[0];
      if (!tab) return;

      chrome.scripting
        .executeScript({ target: { tabId: tab.id }, files: ["content.js"] })
        .then(() => {
          chrome.tabs.sendMessage(tab.id, { action: "TAR_START" }).catch(() => {});
        })
        .catch(() => {
          // Already injected — just send the start message
          chrome.tabs.sendMessage(tab.id, { action: "TAR_START" }).catch(() => {});
        });
    });

    sendResponse({ ok: true });
    return true;
  }

  // Popup: stop recording
  if (msg.action === "TAR_STOP_RECORDING") {
    state.recording = false;
    chrome.storage.local.set({ tarRecording: false });

    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      const tab = tabs[0];
      if (tab) chrome.tabs.sendMessage(tab.id, { action: "TAR_STOP" }).catch(() => {});
    });

    sendResponse({ ok: true });
    return true;
  }

  // Popup: clear
  if (msg.action === "TAR_CLEAR") {
    state.events = [];
    chrome.storage.local.set({ tarEvents: [], tarCode: "" });
    sendResponse({ ok: true });
    return true;
  }
});

// Restore persisted state on service worker startup
chrome.storage.local.get(["tarRecording", "tarEvents"], (data) => {
  state.recording = !!data.tarRecording;
  state.events = data.tarEvents || [];
});
